packages:
  - "packages/*"
  - "services/solver"
  - "services/watchtower"
  - "services/watchtower/packages/*"
  - "services/watchtower/apps/*"
  - "services/gateway"
  - "protocol/sdk"
  - "protocol/packages/*"
