/**
 * ERC-8004 Types
 *
 * Type definitions for ERC-8004 agent discovery and registration.
 * This implements discovery metadata only - no LLM/chat scaffolding.
 */

/**
 * Agent card endpoints configuration.
 * Describes the service endpoints available.
 */
export interface AgentCardEndpoints {
  /** Health check endpoint */
  health: string;
  /** Prometheus metrics endpoint */
  metrics: string;
  /** Execution endpoint (N/A for non-interactive services) */
  execute: string;
}

/**
 * External links for the agent.
 */
export interface AgentCardLinks {
  /** Documentation URL */
  documentation?: string;
  /** Source repository URL */
  repository?: string;
  /** Homepage URL */
  homepage?: string;
}

/**
 * ERC-8004 Agent Card
 *
 * Served at /.well-known/agent-card.json
 * Provides discovery metadata for the solver service.
 */
export interface AgentCard {
  /** Stable agent identifier (derived from service + version) */
  agentId: string;
  /** Human-readable name */
  name: string;
  /** Description of what the agent does */
  description: string;
  /** Semantic version */
  version: string;
  /** List of capabilities */
  capabilities: string[];
  /** Service endpoints */
  endpoints: AgentCardEndpoints;
  /** Supported trust mechanisms (empty for now) */
  supportedTrust: string[];
  /** External links */
  links: AgentCardLinks;
  /** Standards this agent implements */
  standards: string[];
}

/**
 * Registration payload for ERC-8004 registry.
 * Generated by the registration command.
 */
export interface RegistrationPayload {
  /** Agent identity fields */
  agentId: string;
  name: string;
  version: string;
  /** Supported standards */
  standards: string[];
  /** URL to the agent card */
  agentCardUrl: string;
  /** SHA-256 checksum of the agent card JSON */
  agentCardChecksum: string;
  /** Registration timestamp (ISO 8601) */
  registeredAt: string;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Configuration for generating agent card.
 */
export interface AgentCardConfig {
  /** Optional custom agent ID (defaults to derived) */
  agentId?: string;
}
